export const SEARCH_COMMUNE_BY_DISTRICT = 'SEARCH_COMMUNE_BY_DISTRICT';
export const SEARCH_COMMUNE_BY_TEXT = 'SEARCH_COMMUNE_BY_TEXT';
export const FETCHING_DATA = 'FETCHING_DATA';
export const RECIEVED_DATA = 'RECIEVED_DATA';