export const SEARCH_COMMUNE_BY_DISTRICT = 'SEARCH_COMMUNE_BY_DISTRICT';
export const SEARCH_COMMUNE_BY_TEXT = 'SEARCH_COMMUNE_BY_TEXT';
export const FETCHING_DATA = 'FETCHING_DATA';
export const RECIEVED_DATA = 'RECIEVED_DATA';
export const FETCHING_DISTRICT = 'FETCHING_DISTRICT';
export const FETCHED_DISTRICT = 'FETCHED_DISTRICT';
export const FETCH_PROVINCE = 'FETCH_PROVINCE';
export const STOP_FETCH_PROVINCE = 'STOP_FETCH_PROVINCE';